import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { headers } from "next/headers";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BaseBeaty",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const pathname = headersList.get("x-pathname") || "";

  // Check if the current path is dashboard page
  const isDashboard = pathname.startsWith("/dashboard");

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#222222] min-h-screen ${isDashboard ? "" : "flex flex-col"}`}
      >
        {!isDashboard && <Header />}
        {isDashboard ? (
          children
        ) : (
          <main className="grow">
            {children}
          </main>
        )}
        <Toaster />
        {!isDashboard && <Footer />}
      </body>
    </html>
  );
}
